name: Send Email
on:
  push:
    branches:
      - main

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          # SMTP Configuration
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          
          # Email details
          subject: "ğŸ“Œ New Commit to Main"
          to: ErfanMelon@outlook.com,Alireza3205@gmail.com
          from: PhoneixTaskApi
          content_type: text/plain
          body: |
            ğŸš€ A new commit was pushed to the main branch! ğŸ‰

            ğŸ“‚ Repository: ${{ github.repository }}
            âœ‰ï¸ Commit Message: ${{ github.event.head_commit.message }}
            ğŸ‘¤ Author: ${{ github.event.head_commit.author.name }}
            ğŸ”‘ Commit SHA: ${{ github.sha }}
            ğŸ” Compare Changes: ${{ github.event.compare }}
            â° Timestamp: ${{ github.event.head_commit.timestamp }}

            ğŸŒŸ Happy coding! 
            ğŸ”„ Triggered automatically by GitHub Actions
